name: 'Deploying'

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t axegaoshop:latest .

      - name: Save Docker image as tar file
        run: |
          docker save -o axegaoshop.tar axegaoshop:latest
          chmod 664 axegaoshop.tar

      - name: Transfer Docker image to remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_SERVER_ADDRESS }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.PORT }}
          source: axegaoshop.tar
          target: ${{ secrets.REMOTE_SERVER_PATH }}

      - name: Creating docker image
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_SERVER_ADDRESS }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: docker load -i ${{ secrets.REMOTE_SERVER_PATH }}/axegaoshop.tar && rm -f ${{ secrets.REMOTE_SERVER_PATH }}/axegaoshops.tar

      - name: Transfer Docker image to remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_SERVER_ADDRESS }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.PORT }}
          source: docker-compose.yml
          target: ${{ secrets.REMOTE_SERVER_PATH }}

      - name: Starting containers
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_SERVER_ADDRESS }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: docker-compose -f ${{ secrets.REMOTE_SERVER_PATH }}/docker-compose.yml up -d

      - name: Starting migrations
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_SERVER_ADDRESS }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: docker-compose -f ${{ secrets.REMOTE_SERVER_PATH }}/docker-compose.yml exec -T web sh -c 'aerich upgrade'
