name: 'Deploying'
on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t axegaoshop_test:latest .

      - name: Save Docker image as tar file
        run: |
          docker save -o axegaoshop_test.tar axegaoshop_test:latest
          chmod 664 axegaoshop_test.tar

      - name: Transfer Docker image to remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_SERVER_ADDRESS }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.PORT }}
          source: axegaoshop_test.tar
          target: ${{ secrets.REMOTE_SERVER_PATH }}

      - name: Creating docker image
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_SERVER_ADDRESS }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: docker load -i ${{ secrets.REMOTE_SERVER_PATH }}/axegaoshop_test.tar && rm ${{ secrets.REMOTE_SERVER_PATH }}/axegaoshop_test.tar

      - name: Transfer Docker image to remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_SERVER_ADDRESS }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.PORT }}
          source: docker-compose.yml
          target: ${{ secrets.REMOTE_SERVER_PATH }}

      - name: Starting containers
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_SERVER_ADDRESS }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: docker-compose -f ${{ secrets.REMOTE_SERVER_PATH }}/docker-compose.yml up -d

      - name: Starting migrations
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_SERVER_ADDRESS }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: docker-compose -f ${{ secrets.REMOTE_SERVER_PATH }}/docker-compose.yml exec -T web aerich migrate && docker-compose -f ${{ secrets.REMOTE_SERVER_PATH }}/docker-compose.yml exec -T web aerich upgrade
